# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dsan/Documents/Tesi/Codice

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dsan/Documents/Tesi/Codice

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dsan/Documents/Tesi/Codice/CMakeFiles /Users/dsan/Documents/Tesi/Codice/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dsan/Documents/Tesi/Codice/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ArpScanner

# Build rule for target.
ArpScanner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ArpScanner
.PHONY : ArpScanner

# fast build rule for target.
ArpScanner/fast:
	$(MAKE) -f CMakeFiles/ArpScanner.dir/build.make CMakeFiles/ArpScanner.dir/build
.PHONY : ArpScanner/fast

#=============================================================================
# Target rules for targets named pcap_radiotap

# Build rule for target.
pcap_radiotap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcap_radiotap
.PHONY : pcap_radiotap

# fast build rule for target.
pcap_radiotap/fast:
	$(MAKE) -f CMakeFiles/pcap_radiotap.dir/build.make CMakeFiles/pcap_radiotap.dir/build
.PHONY : pcap_radiotap/fast

#=============================================================================
# Target rules for targets named Device

# Build rule for target.
Device: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Device
.PHONY : Device

# fast build rule for target.
Device/fast:
	$(MAKE) -f CMakeFiles/Device.dir/build.make CMakeFiles/Device.dir/build
.PHONY : Device/fast

#=============================================================================
# Target rules for targets named radiotap

# Build rule for target.
radiotap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 radiotap
.PHONY : radiotap

# fast build rule for target.
radiotap/fast:
	$(MAKE) -f CMakeFiles/radiotap.dir/build.make CMakeFiles/radiotap.dir/build
.PHONY : radiotap/fast

#=============================================================================
# Target rules for targets named Pinger

# Build rule for target.
Pinger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Pinger
.PHONY : Pinger

# fast build rule for target.
Pinger/fast:
	$(MAKE) -f CMakeFiles/Pinger.dir/build.make CMakeFiles/Pinger.dir/build
.PHONY : Pinger/fast

#=============================================================================
# Target rules for targets named RadiotapScanner

# Build rule for target.
RadiotapScanner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RadiotapScanner
.PHONY : RadiotapScanner

# fast build rule for target.
RadiotapScanner/fast:
	$(MAKE) -f CMakeFiles/RadiotapScanner.dir/build.make CMakeFiles/RadiotapScanner.dir/build
.PHONY : RadiotapScanner/fast

ArpScanner.o: ArpScanner.cpp.o

.PHONY : ArpScanner.o

# target to build an object file
ArpScanner.cpp.o:
	$(MAKE) -f CMakeFiles/ArpScanner.dir/build.make CMakeFiles/ArpScanner.dir/ArpScanner.cpp.o
.PHONY : ArpScanner.cpp.o

ArpScanner.i: ArpScanner.cpp.i

.PHONY : ArpScanner.i

# target to preprocess a source file
ArpScanner.cpp.i:
	$(MAKE) -f CMakeFiles/ArpScanner.dir/build.make CMakeFiles/ArpScanner.dir/ArpScanner.cpp.i
.PHONY : ArpScanner.cpp.i

ArpScanner.s: ArpScanner.cpp.s

.PHONY : ArpScanner.s

# target to generate assembly for a file
ArpScanner.cpp.s:
	$(MAKE) -f CMakeFiles/ArpScanner.dir/build.make CMakeFiles/ArpScanner.dir/ArpScanner.cpp.s
.PHONY : ArpScanner.cpp.s

Device.o: Device.cpp.o

.PHONY : Device.o

# target to build an object file
Device.cpp.o:
	$(MAKE) -f CMakeFiles/Device.dir/build.make CMakeFiles/Device.dir/Device.cpp.o
.PHONY : Device.cpp.o

Device.i: Device.cpp.i

.PHONY : Device.i

# target to preprocess a source file
Device.cpp.i:
	$(MAKE) -f CMakeFiles/Device.dir/build.make CMakeFiles/Device.dir/Device.cpp.i
.PHONY : Device.cpp.i

Device.s: Device.cpp.s

.PHONY : Device.s

# target to generate assembly for a file
Device.cpp.s:
	$(MAKE) -f CMakeFiles/Device.dir/build.make CMakeFiles/Device.dir/Device.cpp.s
.PHONY : Device.cpp.s

Pinger.o: Pinger.cpp.o

.PHONY : Pinger.o

# target to build an object file
Pinger.cpp.o:
	$(MAKE) -f CMakeFiles/Pinger.dir/build.make CMakeFiles/Pinger.dir/Pinger.cpp.o
.PHONY : Pinger.cpp.o

Pinger.i: Pinger.cpp.i

.PHONY : Pinger.i

# target to preprocess a source file
Pinger.cpp.i:
	$(MAKE) -f CMakeFiles/Pinger.dir/build.make CMakeFiles/Pinger.dir/Pinger.cpp.i
.PHONY : Pinger.cpp.i

Pinger.s: Pinger.cpp.s

.PHONY : Pinger.s

# target to generate assembly for a file
Pinger.cpp.s:
	$(MAKE) -f CMakeFiles/Pinger.dir/build.make CMakeFiles/Pinger.dir/Pinger.cpp.s
.PHONY : Pinger.cpp.s

RadiotapScanner.o: RadiotapScanner.cpp.o

.PHONY : RadiotapScanner.o

# target to build an object file
RadiotapScanner.cpp.o:
	$(MAKE) -f CMakeFiles/RadiotapScanner.dir/build.make CMakeFiles/RadiotapScanner.dir/RadiotapScanner.cpp.o
.PHONY : RadiotapScanner.cpp.o

RadiotapScanner.i: RadiotapScanner.cpp.i

.PHONY : RadiotapScanner.i

# target to preprocess a source file
RadiotapScanner.cpp.i:
	$(MAKE) -f CMakeFiles/RadiotapScanner.dir/build.make CMakeFiles/RadiotapScanner.dir/RadiotapScanner.cpp.i
.PHONY : RadiotapScanner.cpp.i

RadiotapScanner.s: RadiotapScanner.cpp.s

.PHONY : RadiotapScanner.s

# target to generate assembly for a file
RadiotapScanner.cpp.s:
	$(MAKE) -f CMakeFiles/RadiotapScanner.dir/build.make CMakeFiles/RadiotapScanner.dir/RadiotapScanner.cpp.s
.PHONY : RadiotapScanner.cpp.s

pcap_radiotap.o: pcap_radiotap.cpp.o

.PHONY : pcap_radiotap.o

# target to build an object file
pcap_radiotap.cpp.o:
	$(MAKE) -f CMakeFiles/pcap_radiotap.dir/build.make CMakeFiles/pcap_radiotap.dir/pcap_radiotap.cpp.o
.PHONY : pcap_radiotap.cpp.o

pcap_radiotap.i: pcap_radiotap.cpp.i

.PHONY : pcap_radiotap.i

# target to preprocess a source file
pcap_radiotap.cpp.i:
	$(MAKE) -f CMakeFiles/pcap_radiotap.dir/build.make CMakeFiles/pcap_radiotap.dir/pcap_radiotap.cpp.i
.PHONY : pcap_radiotap.cpp.i

pcap_radiotap.s: pcap_radiotap.cpp.s

.PHONY : pcap_radiotap.s

# target to generate assembly for a file
pcap_radiotap.cpp.s:
	$(MAKE) -f CMakeFiles/pcap_radiotap.dir/build.make CMakeFiles/pcap_radiotap.dir/pcap_radiotap.cpp.s
.PHONY : pcap_radiotap.cpp.s

radiotap.o: radiotap.c.o

.PHONY : radiotap.o

# target to build an object file
radiotap.c.o:
	$(MAKE) -f CMakeFiles/radiotap.dir/build.make CMakeFiles/radiotap.dir/radiotap.c.o
.PHONY : radiotap.c.o

radiotap.i: radiotap.c.i

.PHONY : radiotap.i

# target to preprocess a source file
radiotap.c.i:
	$(MAKE) -f CMakeFiles/radiotap.dir/build.make CMakeFiles/radiotap.dir/radiotap.c.i
.PHONY : radiotap.c.i

radiotap.s: radiotap.c.s

.PHONY : radiotap.s

# target to generate assembly for a file
radiotap.c.s:
	$(MAKE) -f CMakeFiles/radiotap.dir/build.make CMakeFiles/radiotap.dir/radiotap.c.s
.PHONY : radiotap.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ArpScanner"
	@echo "... pcap_radiotap"
	@echo "... Device"
	@echo "... edit_cache"
	@echo "... radiotap"
	@echo "... Pinger"
	@echo "... RadiotapScanner"
	@echo "... install"
	@echo "... ArpScanner.o"
	@echo "... ArpScanner.i"
	@echo "... ArpScanner.s"
	@echo "... Device.o"
	@echo "... Device.i"
	@echo "... Device.s"
	@echo "... Pinger.o"
	@echo "... Pinger.i"
	@echo "... Pinger.s"
	@echo "... RadiotapScanner.o"
	@echo "... RadiotapScanner.i"
	@echo "... RadiotapScanner.s"
	@echo "... pcap_radiotap.o"
	@echo "... pcap_radiotap.i"
	@echo "... pcap_radiotap.s"
	@echo "... radiotap.o"
	@echo "... radiotap.i"
	@echo "... radiotap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

